server:
  port: 80


spring:
  application:
    name: cloud-order-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      test-while-idle: false
  devtools:
    livereload:
      enabled: true
eureka:

  client:
    #   是否将自己注册进EurekaServer默认位true
    register-with-eureka: false
    #    是否从EurekaServer抓取自己已有的注册信息，默认位true，单节点无所谓，集群必须是true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka  #  集群版



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: edu.ahau.springcloud.entities    # 所有Entity别名类所在包