server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
    prefer-ip-address: true
  client:
    register-with-eureka: false #false 不往注册中心注册
    fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ #和7002相互注册
#      defaultZone: http://eureka7001.com:7001/eureka/ # 单机版指向自己
  server:
    # 关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    # 留存时间2S
    eviction-interval-timer-in-ms: 2000