server:
  port: 8004

# 服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      test-while-idle: false
    devtools:
      livereload:
        enabled: true
  cloud:
    zookeeper:
      # 一个zookeeper的机器IP以及端口号
      connect-string: 192.168.233.130:2181

